import { createRequire } from "module";
import { describe, expect, it } from "vitest";

const require = createRequire(import.meta.url);
const { validateOfficeToolCall } = require("./officeToolValidation");

describe("office tool validation", () => {
  it("accepts valid Office tool calls", () => {
    expect(() => validateOfficeToolCall("word", "get_document_part", { address: "section[1]" })).not.toThrow();
    expect(() => validateOfficeToolCall("word", "get_document_range", { address: "table[1].cell[2,3]", format: "html" })).not.toThrow();
    expect(() => validateOfficeToolCall("excel", "set_selected_range", { data: [[1, true, "x"]] })).not.toThrow();
    expect(() => validateOfficeToolCall("excel", "manage_range", { action: "sort", range: "A1:C10", sortKey: 0 })).not.toThrow();
    expect(() => validateOfficeToolCall("excel", "manage_range", { action: "filter", range: "A1:C10", filterOn: "Values", filterValues: ["North"], columnIndex: 0 })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide", { action: "clear", slideIndex: 0 })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide", { action: "create", targetIndex: 0 })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "get_presentation_structure", { format: "both" })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "add_slide_animation", { type: "motionPath", start: "afterPrevious", path: "M 0 0 L 0.25 0 E", shapeId: ["shape-1"] })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "add_slide_animation", { type: "fade", start: "onClick", shapeId: 7 })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "get_slide_animations", { slideIndex: 0 })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "execute_office_js", { code: "await sync(); return { ok: true };" })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "list_slide_shapes", { slideIndex: 0, detail: true })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "read_slide_text", { ref: "slide-id:256/shape:4" })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_text", { ref: "slide-id:256/shape:4", paragraphsXml: ["<a:p xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\"><a:r><a:t>Hello</a:t></a:r></a:p>"] })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_xml", { replacements: [{ ref: "slide-id:256/shape:4", paragraphsXml: ["<a:p xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\"><a:endParaRPr lang=\"en-US\"/></a:p>"] }] })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_xml", { slideIndex: 0, code: "const xml = await zip.file(slidePath).async('string'); setResult({ size: xml.length });", autosize_shape_ids: [10, "11"] })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_chart", { action: "update", ref: "slide-id:256/shape:8", chartType: "bar", categories: ["North"], series: [{ name: "Revenue", values: [12] }] })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_master", { themeColors: { Accent1: "#123ABC" } })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "get_slide_layout_details", { layoutId: "layout-1" })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "list_slide_layouts", {})).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "duplicate_slide", { slideIndex: 0, targetIndex: 1 })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "create_slide_from_layout", { layoutId: "layout-1", bindings: [{ placeholderType: "Title", text: "Quarterly review" }] })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "set_slide_transition", { effect: "fade" })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_media", { action: "replaceImage", slideIndex: 0, shapeId: "shape-1", imageUrl: "https://example.com/a.png" })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_table", { action: "update", slideIndex: 0, shapeId: "shape-1", values: [["A", 1]] })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "set_slide_notes", { notes: "Hello" })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "clear_slide_animations", {})).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_shapes", { action: "update", slideIndex: 0, shapeId: "shape-1", text: "Hello" })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_shapes", { action: "update", text: "Hello" })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_shapes", { action: "create", slideIndex: 0, shapeType: "line", width: -20, height: 10 })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_media", { action: "insertImage", slideIndex: 0, imageUrl: "https://example.com/a.png" })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_table", { action: "create", slideIndex: 0, values: [["A", 1, true]] })).not.toThrow();
    expect(() => validateOfficeToolCall("onenote", "get_page_content", { format: "summary" })).not.toThrow();
    expect(() => validateOfficeToolCall("onenote", "set_note_selection", { content: "Hello", coercionType: "text" })).not.toThrow();
    expect(() => validateOfficeToolCall("onenote", "navigate_to_page", { pageId: "page-1" })).not.toThrow();
  });

  it("rejects invalid hosts and payload shapes", () => {
    expect(() => validateOfficeToolCall("excel", "get_document_part", { address: "section[1]" })).toThrow(/not available/);
    expect(() => validateOfficeToolCall("word", "get_document_part", {})).toThrow(/Missing required args.address/);
    expect(() => validateOfficeToolCall("word", "set_document_range", { address: "selection", location: "middle" })).toThrow(/expected one of/);
    expect(() => validateOfficeToolCall("word", "set_document_range", { address: "selection" })).toThrow(/args.content/);
    expect(() => validateOfficeToolCall("excel", "manage_range", { action: "filter", range: "A1:C10", filterOn: "Values", filterValues: ["North"] })).toThrow(/columnIndex/);
    expect(() => validateOfficeToolCall("onenote", "set_note_selection", {})).toThrow(/args.content/);
    expect(() => validateOfficeToolCall("onenote", "set_note_selection", { content: "   " })).toThrow(/cannot be empty/);
    expect(() => validateOfficeToolCall("onenote", "set_page_title", { title: "   " })).toThrow(/cannot be empty/);
    expect(() => validateOfficeToolCall("onenote", "append_page_content", { html: "   " })).toThrow(/cannot be empty/);
    expect(() => validateOfficeToolCall("powerpoint", "add_slide_from_code", { code: "   " })).toThrow(/Unknown Office tool/);
    expect(() => validateOfficeToolCall("powerpoint", "add_slide_animation", { type: "motionPath", start: "onClick" })).toThrow(/args\.path/);
    expect(() => validateOfficeToolCall("powerpoint", "add_slide_animation", { type: "rotate", start: "onClick" })).toThrow(/args\.angleDegrees/);
    expect(() => validateOfficeToolCall("powerpoint", "add_slide_animation", { type: "changeFillColor", start: "onClick" })).toThrow(/args\.toColor/);
    expect(() => validateOfficeToolCall("powerpoint", "add_slide_animation", { type: "fade", start: "onClick", shapeId: [] })).toThrow(/args\.shapeId/);
    expect(() => validateOfficeToolCall("powerpoint", "execute_office_js", { code: "   " })).toThrow(/cannot be empty/);
    expect(() => validateOfficeToolCall("powerpoint", "read_slide_text", { ref: "   " })).toThrow(/cannot be empty/);
    expect(() => validateOfficeToolCall("powerpoint", "read_slide_text", { ref: "shape:4" })).toThrow(/args\.ref/);
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_text", { ref: "slide-id:256\/shape:4", paragraphsXml: [] })).not.toThrow();
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_xml", { replacements: [] })).toThrow(/at least one replacement/);
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_xml", {})).toThrow(/args\.code|args\.replacements|Provide args.code or args.replacements/);
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_xml", { code: "   " })).toThrow(/cannot be empty/);
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_xml", { code: "return 1;", replacements: [{ ref: "slide-id:256/shape:4", paragraphsXml: [] }] })).toThrow(/either args\.code or args\.replacements|not both/);
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_chart", { action: "delete" })).toThrow(/args\.ref/);
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_chart", { action: "update", ref: "slide-id:256/shape:8", chartType: "bar", series: [] })).toThrow(/args\.series/);
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_chart", { action: "create", slideIndex: 0, chartType: "bar", series: [{ name: "Revenue", values: [12] }], width: 0 })).toThrow(/args\.width/);
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_master", {})).toThrow(/args\.themeColors|args\.decorativeShapes/);
    expect(() => validateOfficeToolCall("powerpoint", "edit_slide_master", { themeColors: { Accent1: "blue" } })).toThrow(/args\.themeColors\.Accent1/);
    expect(() => validateOfficeToolCall("powerpoint", "create_slide_from_layout", { layoutId: "layout-1", bindings: [{ text: "Quarterly review" }] })).toThrow(/placeholderType or placeholderName/);
    expect(() => validateOfficeToolCall("powerpoint", "create_slide_from_layout", { layoutId: "layout-1", bindings: [{ placeholderName: "Hero", imageUrl: "http://example.com/a.png" }] })).toThrow(/args\.bindings\[0\]\.imageUrl/);
    expect(() => validateOfficeToolCall("powerpoint", "create_slide_from_layout", { layoutId: "layout-1", bindings: [{ placeholderName: "Table", tableData: [["A", "B"], [1]] }] })).toThrow(/args\.bindings\[0\]\.tableData/);
    expect(() => validateOfficeToolCall("powerpoint", "set_slide_transition", { effect: "randomBar", direction: "left" })).toThrow(/args\.direction/);
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide", { action: "duplicate", sourceIndex: 0 })).toThrow(/expected one of/);
    expect(() => validateOfficeToolCall("powerpoint", "set_slide_transition", { effect: "split", direction: "left" })).toThrow(/args\.direction/);
    expect(() => validateOfficeToolCall("powerpoint", "set_slide_transition", { effect: "fade", slideIndex: [] })).toThrow(/args\.slideIndex/);
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_media", { action: "replaceImage", slideIndex: 0 })).toThrow(/args\.imageUrl|args\.shapeId/);
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_table", { action: "update", slideIndex: 0, values: [["A"]] })).toThrow(/args\.shapeId/);
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_table", { action: "create", slideIndex: 0, values: [] })).toThrow(/args\.values/);
    expect(() => validateOfficeToolCall("powerpoint", "get_slide_shapes", { slideIndex: 0 })).toThrow(/Unknown Office tool/);
    expect(() => validateOfficeToolCall("powerpoint", "manage_slide_chart", { action: "create" })).toThrow(/Unknown Office tool/);
    expect(() => validateOfficeToolCall("powerpoint", "insert_business_layout", { layoutType: "timeline" })).toThrow(/Unknown Office tool/);
    expect(() => validateOfficeToolCall("powerpoint", "create_slide_from_template", { layoutId: "layout-1" })).toThrow(/Unknown Office tool/);
    expect(() => validateOfficeToolCall("onenote", "navigate_to_page", {})).toThrow(/exactly one/);
    expect(() => validateOfficeToolCall("onenote", "navigate_to_page", { pageId: "page-1", clientUrl: "https://example.invalid" })).toThrow(/exactly one/);
    expect(() => validateOfficeToolCall("word", "get_document_part", { address: "x", extra: true })).toThrow(/Unexpected args.extra/);
    expect(() => validateOfficeToolCall("powerpoint", "get_presentation_structure", { format: "yaml" })).toThrow(/expected one of/);
    expect(() => validateOfficeToolCall("word", "__proto__", {})).toThrow(/Unknown Office tool/);
  });
});
