import { tool } from "@opencode-ai/plugin"
import { powerpoint } from "../lib/office-powerpoint"

export default powerpoint("edit_slide_master", "Update supported PowerPoint slide master theme colors and decorative master shapes.", {
  slideMasterId: tool.schema.string().optional().describe("Optional slide master id. Defaults to the first slide master."),
  themeColors: tool.schema.object({
  Dark1: tool.schema.string().optional(),
  Light1: tool.schema.string().optional(),
  Dark2: tool.schema.string().optional(),
  Light2: tool.schema.string().optional(),
  Accent1: tool.schema.string().optional(),
  Accent2: tool.schema.string().optional(),
  Accent3: tool.schema.string().optional(),
  Accent4: tool.schema.string().optional(),
  Accent5: tool.schema.string().optional(),
  Accent6: tool.schema.string().optional(),
  Hyperlink: tool.schema.string().optional(),
  FollowedHyperlink: tool.schema.string().optional(),
}).optional().describe("Optional theme color patch for the chosen slide master."),
  decorativeShapes: tool.schema.array(tool.schema.union([tool.schema.object({
  action: tool.schema.enum(["create"]),
  shapeType: tool.schema.enum(["textBox", "geometricShape"]),
  geometricShapeType: tool.schema.string().optional(),
  text: tool.schema.string().optional(),
  name: tool.schema.string().optional(),
  left: tool.schema.number().optional(),
  top: tool.schema.number().optional(),
  width: tool.schema.number().optional(),
  height: tool.schema.number().optional(),
  visible: tool.schema.boolean().optional(),
  fillColor: tool.schema.string().optional(),
  lineColor: tool.schema.string().optional(),
  lineWeight: tool.schema.number().optional(),
  fontColor: tool.schema.string().optional(),
  fontSize: tool.schema.number().optional(),
}), tool.schema.object({
  action: tool.schema.enum(["update"]),
  shapeId: tool.schema.string(),
  text: tool.schema.string().optional(),
  name: tool.schema.string().optional(),
  left: tool.schema.number().optional(),
  top: tool.schema.number().optional(),
  width: tool.schema.number().optional(),
  height: tool.schema.number().optional(),
  visible: tool.schema.boolean().optional(),
  fillColor: tool.schema.string().optional(),
  lineColor: tool.schema.string().optional(),
  lineWeight: tool.schema.number().optional(),
  fontColor: tool.schema.string().optional(),
  fontSize: tool.schema.number().optional(),
}), tool.schema.object({
  action: tool.schema.enum(["delete"]),
  shapeId: tool.schema.string(),
})])).optional().describe("Optional decorative slide master shape operations."),
})
