import { tool } from "@opencode-ai/plugin"
import { powerpoint } from "../lib/office-powerpoint"

export default powerpoint("edit_slide_xml", "Primary tool for most edits to existing content on one PowerPoint slide. Exports one slide as a ZIP package, provides slideXml as a live XMLDocument (already parsed, not a string), and reimports the edited slide in one round-trip. Mutate slideXml in place with DOM APIs — changes are serialized automatically. Use it by default for existing-slide text rewrites, batch text edits across shapes, advanced formatting, structural shape work, shape geometry/style fixes, and any slide-scoped edit that benefits from full OOXML fidelity. Prefer this over manage_slide_shapes for most edits to existing shapes, and over execute_office_js unless the host API is specifically required.", {
  mode: tool.schema.enum(["code", "replacements"]).describe("Required discriminator. Use \"code\" for general XML DOM edits, or \"replacements\" for the legacy text-only multi-shape replacement shorthand."),
  slideIndex: tool.schema.number().optional().describe("Optional 0-based slide index. Required when no active slide can be inferred safely. Use this for arbitrary single-slide XML edits."),
  code: tool.schema.string().optional().describe("Required when mode is \"code\". Async JavaScript function body. Key variables in scope: slideXml and doc (same object) are a live XMLDocument — already parsed, not a string. Mutate it in place with standard DOM APIs (getElementsByTagNameNS, createElement, appendChild, setAttribute, etc.) and changes are saved automatically. Do not re-parse slideXml with DOMParser. Also available: xml (a let-bound string snapshot of the slide XML), zip (JSZip-style single-slide package supporting zip.file(path) and zip.files[path]), slidePath (always ppt/slides/slide1.xml regardless of deck position), namespaces ({ a, p, r } namespace URIs), escapeXml(str), parseXml(str), serializeXml(doc), console, setResult(value), DOMParser, and XMLSerializer. You can also return an XML string or XMLDocument to replace the slide, or write via zip.file(slidePath, xmlString)."),
  autosize_shape_ids: tool.schema.array(tool.schema.union([tool.schema.string(), tool.schema.number()])).optional().describe("Optional XML cNvPr shape ids whose current text auto-size settings should be preserved after the edited slide is reimported."),
  replacements: tool.schema.array(tool.schema.object({
  ref: tool.schema.string().describe("Stable shape ref in the format slide-id:<slideId>/shape:<xmlShapeId>."),
  paragraphsXml: tool.schema.array(tool.schema.string()).describe("Replacement raw <a:p> paragraph XML for the targeted shape."),
})).optional().describe("Required when mode is \"replacements\". Legacy shorthand for text-only multi-shape updates on one slide. Prefer code for general slide XML edits, but still prefer this tool over manage_slide_shapes when updating existing copy across shapes on one slide."),
})
