import { tool } from "@opencode-ai/plugin"
import { powerpoint } from "../lib/office-powerpoint"

export default powerpoint("manage_slide_shapes", "Create, update, delete, group, or ungroup PowerPoint shapes for geometry, styling, naming, and structure changes. For wording or rich-text edits, prefer read_slide_text plus edit_slide_text or edit_slide_xml. Updates are patch-like: pass a target plus only the properties you want to change, and omit unchanged/default values.", {
  action: tool.schema.enum(["create", "update", "delete", "group", "ungroup"]).describe("Shape operation to perform. Use update as a sparse patch: include only targeting fields and the properties that should change."),
  slideIndex: tool.schema.union([tool.schema.number(), tool.schema.array(tool.schema.number())]).optional().describe("0-based slide index. Optional when the active slide can be inferred from the current selection."),
  shapeId: tool.schema.string().optional().describe("Existing shape id. Preferred targeting field for update/delete/ungroup when available."),
  shapeIndex: tool.schema.number().optional().describe("Existing 0-based shape index on the slide. Use this only when shapeId is unavailable."),
  shapeIds: tool.schema.array(tool.schema.union([tool.schema.string(), tool.schema.number()])).optional().describe("Array of shape ids to group together. Required for the group action. Must contain at least 2 shapes."),
  placeholderType: tool.schema.string().optional().describe("Optional placeholder type to target for update or delete, such as Title, Body, Subtitle, or Content. Use this instead of shapeId/shapeIndex when targeting a placeholder by role."),
  shapeType: tool.schema.enum(["textBox", "geometricShape", "line"]).optional().describe("Shape type to create. Create-only; omit for update/delete/group/ungroup."),
  geometricShapeType: tool.schema.string().optional().describe("Geometric shape type for create. Must be a valid PowerPoint.GeometricShapeType value such as Rectangle, Ellipse, Chevron, or RightArrow. Create-only."),
  connectorType: tool.schema.enum(["Straight", "Elbow", "Curve"]).optional().describe("Optional connector type for line creation. Default Straight. Create-only."),
  text: tool.schema.string().optional().describe("Text content to create or replace. Best for simple labels or newly created shapes. For fidelity-sensitive wording changes, prefer read_slide_text plus edit_slide_text, or edit_slide_xml for several text shapes on one slide."),
  name: tool.schema.string().optional().describe("Descriptive shape name for identification and animation targeting. Use semantic names like 'Bullet 1 - Revenue' or 'Hero Image'."),
  left: tool.schema.number().optional().describe("Left position in points. For update, omit to keep the current position."),
  top: tool.schema.number().optional().describe("Top position in points. For update, omit to keep the current position."),
  width: tool.schema.number().optional().describe("Width in points. For update, omit to keep the current width."),
  height: tool.schema.number().optional().describe("Height in points. For update, omit to keep the current height."),
  rotation: tool.schema.number().optional().describe("Rotation in degrees. For update, omit to keep the current rotation."),
  visible: tool.schema.boolean().optional().describe("Whether the shape is visible. For update, omit to leave visibility unchanged."),
  altTextTitle: tool.schema.string().optional().describe("Alt text title. For update, omit to leave unchanged."),
  altTextDescription: tool.schema.string().optional().describe("Alt text description. For update, omit to leave unchanged."),
  fillColor: tool.schema.string().optional().describe("Solid fill color. For update, omit to leave fill unchanged. Do not send empty strings as placeholders."),
  fillTransparency: tool.schema.number().optional().describe("Fill transparency from 0 to 1. For update, omit to leave unchanged."),
  clearFill: tool.schema.boolean().optional().describe("Clear the fill entirely. For update, include only when you intentionally want no fill."),
  lineColor: tool.schema.string().optional().describe("Line color. For update, omit to leave unchanged. Do not send empty strings as placeholders."),
  lineWeight: tool.schema.number().optional().describe("Line weight in points. For update, omit to leave unchanged."),
  lineTransparency: tool.schema.number().optional().describe("Line transparency from 0 to 1. For update, omit to leave unchanged."),
  lineVisible: tool.schema.boolean().optional().describe("Whether the line is visible. For update, omit to leave unchanged."),
  fontName: tool.schema.string().optional().describe("Font family name. For update, omit to leave unchanged. Do not send empty strings as placeholders."),
  fontSize: tool.schema.number().optional().describe("Font size in points. For update, omit to leave unchanged."),
  fontColor: tool.schema.string().optional().describe("Font color. For update, omit to leave unchanged. Do not send empty strings as placeholders."),
  bold: tool.schema.boolean().optional(),
  italic: tool.schema.boolean().optional(),
  underline: tool.schema.enum(["None", "Single", "Double", "Heavy", "Dotted", "DottedHeavy", "Dash", "DashHeavy", "DashLong", "DashLongHeavy", "DotDash", "DotDashHeavy", "DotDotDash", "DotDotDashHeavy", "Wavy", "WavyHeavy", "WavyDouble"]).optional(),
  strikethrough: tool.schema.boolean().optional(),
  allCaps: tool.schema.boolean().optional(),
  smallCaps: tool.schema.boolean().optional(),
  subscript: tool.schema.boolean().optional(),
  superscript: tool.schema.boolean().optional(),
  doubleStrikethrough: tool.schema.boolean().optional(),
  paragraphAlignment: tool.schema.enum(["Left", "Center", "Right", "Justify", "JustifyLow", "Distributed", "ThaiDistributed"]).optional(),
  bulletVisible: tool.schema.boolean().optional(),
  indentLevel: tool.schema.number().optional(),
  textAutoSize: tool.schema.enum(["AutoSizeNone", "AutoSizeTextToFitShape", "AutoSizeShapeToFitText"]).optional(),
  wordWrap: tool.schema.boolean().optional(),
  verticalAlignment: tool.schema.enum(["Top", "Middle", "Bottom", "TopCentered", "MiddleCentered", "BottomCentered"]).optional(),
  marginLeft: tool.schema.number().optional().describe("Left text margin in points. For update, omit to leave unchanged."),
  marginRight: tool.schema.number().optional().describe("Right text margin in points. For update, omit to leave unchanged."),
  marginTop: tool.schema.number().optional().describe("Top text margin in points. For update, omit to leave unchanged."),
  marginBottom: tool.schema.number().optional().describe("Bottom text margin in points. For update, omit to leave unchanged."),
})
