import { tool } from "@opencode-ai/plugin"
import { powerpoint } from "../lib/office-powerpoint"

export default powerpoint("manage_slide_shapes", "Create, update, or delete PowerPoint shapes with generic geometry, styling, and text formatting controls.", {
  action: tool.schema.enum(["create", "update", "delete"]).describe("Shape operation to perform."),
  slideIndex: tool.schema.number().describe("0-based slide index."),
  shapeId: tool.schema.string().optional().describe("Existing shape id. Preferred over shapeIndex when available."),
  shapeIndex: tool.schema.number().optional().describe("Existing 0-based shape index on the slide."),
  placeholderType: tool.schema.string().optional().describe("Optional placeholder type to target for update or delete, such as Title, Body, Subtitle, or Content."),
  shapeType: tool.schema.enum(["textBox", "geometricShape", "line"]).optional().describe("Shape type to create."),
  geometricShapeType: tool.schema.string().optional().describe("Geometric shape type for create. Must be a valid PowerPoint.GeometricShapeType value such as Rectangle, Ellipse, Chevron, or RightArrow."),
  connectorType: tool.schema.enum(["Straight", "Elbow", "Curve"]).optional().describe("Optional connector type for line creation. Default Straight."),
  text: tool.schema.string().optional().describe("Text content to set or create."),
  name: tool.schema.string().optional().describe("Descriptive shape name for identification and animation targeting. Use semantic names like 'Bullet 1 - Revenue' or 'Hero Image'."),
  left: tool.schema.number().optional(),
  top: tool.schema.number().optional(),
  width: tool.schema.number().optional(),
  height: tool.schema.number().optional(),
  rotation: tool.schema.number().optional(),
  visible: tool.schema.boolean().optional(),
  altTextTitle: tool.schema.string().optional(),
  altTextDescription: tool.schema.string().optional(),
  fillColor: tool.schema.string().optional(),
  fillTransparency: tool.schema.number().optional(),
  clearFill: tool.schema.boolean().optional(),
  lineColor: tool.schema.string().optional(),
  lineWeight: tool.schema.number().optional(),
  lineTransparency: tool.schema.number().optional(),
  lineVisible: tool.schema.boolean().optional(),
  fontName: tool.schema.string().optional(),
  fontSize: tool.schema.number().optional(),
  fontColor: tool.schema.string().optional(),
  bold: tool.schema.boolean().optional(),
  italic: tool.schema.boolean().optional(),
  underline: tool.schema.enum(["None", "Single", "Double", "Heavy", "Dotted", "DottedHeavy", "Dash", "DashHeavy", "DashLong", "DashLongHeavy", "DotDash", "DotDashHeavy", "DotDotDash", "DotDotDashHeavy", "Wavy", "WavyHeavy", "WavyDouble"]).optional(),
  strikethrough: tool.schema.boolean().optional(),
  allCaps: tool.schema.boolean().optional(),
  smallCaps: tool.schema.boolean().optional(),
  subscript: tool.schema.boolean().optional(),
  superscript: tool.schema.boolean().optional(),
  doubleStrikethrough: tool.schema.boolean().optional(),
  paragraphAlignment: tool.schema.enum(["Left", "Center", "Right", "Justify", "JustifyLow", "Distributed", "ThaiDistributed"]).optional(),
  bulletVisible: tool.schema.boolean().optional(),
  indentLevel: tool.schema.number().optional(),
  textAutoSize: tool.schema.enum(["AutoSizeNone", "AutoSizeTextToFitShape", "AutoSizeShapeToFitText"]).optional(),
  wordWrap: tool.schema.boolean().optional(),
  verticalAlignment: tool.schema.enum(["Top", "Middle", "Bottom", "TopCentered", "MiddleCentered", "BottomCentered"]).optional(),
  marginLeft: tool.schema.number().optional(),
  marginRight: tool.schema.number().optional(),
  marginTop: tool.schema.number().optional(),
  marginBottom: tool.schema.number().optional(),
})
