import { describe, expect, it } from "vitest";
import { getOfficeToolNames } from "./office-tool-definitions";

describe("office tool definitions", () => {
  it("filters tool names by host", () => {
    expect(getOfficeToolNames("word")).toContain("get_document_content");
    expect(getOfficeToolNames("word")).toContain("set_document_part");
    expect(getOfficeToolNames("word")).toContain("get_document_range");
    expect(getOfficeToolNames("word")).toContain("get_document_targets");
    expect(getOfficeToolNames("word")).not.toContain("manage_chart");
    expect(getOfficeToolNames("excel")).toContain("manage_chart");
    expect(getOfficeToolNames("excel")).toContain("manage_named_range");
    expect(getOfficeToolNames("excel")).toContain("manage_range");
    expect(getOfficeToolNames("excel")).not.toContain("manage_slide");
    expect(getOfficeToolNames("powerpoint")).toContain("manage_slide");
    expect(getOfficeToolNames("powerpoint")).toContain("manage_slide_shapes");
    expect(getOfficeToolNames("powerpoint")).toContain("add_slide_animation");
    expect(getOfficeToolNames("powerpoint")).toContain("clear_slide_animations");
    expect(getOfficeToolNames("powerpoint")).toContain("get_slide_animations");
    expect(getOfficeToolNames("powerpoint")).toContain("execute_office_js");
    expect(getOfficeToolNames("powerpoint")).toContain("get_slide_notes");
    expect(getOfficeToolNames("powerpoint")).toContain("get_slide_transition");
    expect(getOfficeToolNames("powerpoint")).toContain("list_slide_shapes");
    expect(getOfficeToolNames("powerpoint")).toContain("read_slide_text");
    expect(getOfficeToolNames("powerpoint")).toContain("edit_slide_text");
    expect(getOfficeToolNames("powerpoint")).toContain("edit_slide_xml");
    expect(getOfficeToolNames("powerpoint")).toContain("edit_slide_chart");
    expect(getOfficeToolNames("powerpoint")).toContain("edit_slide_master");
    expect(getOfficeToolNames("powerpoint")).toContain("get_slide_layout_details");
    expect(getOfficeToolNames("powerpoint")).toContain("list_slide_layouts");
    expect(getOfficeToolNames("powerpoint")).toContain("duplicate_slide");
    expect(getOfficeToolNames("powerpoint")).toContain("create_slide_from_layout");
    expect(getOfficeToolNames("powerpoint")).toContain("manage_slide_media");
    expect(getOfficeToolNames("powerpoint")).toContain("manage_slide_table");
    expect(getOfficeToolNames("powerpoint")).toContain("set_slide_notes");
    expect(getOfficeToolNames("powerpoint")).toContain("set_slide_transition");
    expect(getOfficeToolNames("powerpoint")).not.toContain("add_slide_from_code");
    expect(getOfficeToolNames("powerpoint")).not.toContain("get_selection_text");
  });
});
